# Build Stage
FROM maven:3.9.6-eclipse-temurin-21-alpine AS build
WORKDIR /app
COPY pom.xml .
COPY ultron-common/pom.xml ultron-common/
COPY ultron-simulator/pom.xml ultron-simulator/
COPY ultron-ingestion/pom.xml ultron-ingestion/
COPY ultron-detector/pom.xml ultron-detector/
COPY ultron-rca/pom.xml ultron-rca/
COPY ultron-api/pom.xml ultron-api/
COPY . .
RUN mvn clean package -DskipTests -pl ultron-common,ultron-detector -am

# Run Stage
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/ultron-detector/target/ultron-detector-*.jar app.jar
COPY --from=build /app/ultron-common/src/main/resources/ca.pem /app/ca.pem
EXPOSE 8080
ENTRYPOINT ["java", "-Xmx300m", "-jar", "app.jar", "--spring.profiles.active=prod", "--spring.kafka.properties.ssl.truststore.location=/app/ca.pem"]
